<?php

/**
 * @file
 * Provide a static tab which triggers a popup for sending a question to
 * Biblioteksvagten.dk.
 */

/**
 * Implements hook_menu().
 */
function ding_bv_menu() {
  $items['admin/config/services/ding_bv'] = array(
    'title' => 'Ask Biblioteksvagten.dk',
    'description' => 'Configure the tab for sending user questions to Biblioteksvagten.dk.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_bv_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_bv.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_build().
 */
function ding_bv_page_build(&$page) {
  if ($agency_id = variable_get('ting_agency', '')) {
    $agency_id = 'DK-' . $agency_id;
  }
  else {
    $agency_id = variable_get('ding_bv_agency_id', '');
  }

  if (!$agency_id) {
    return;
  }

  // JavaScript settings var.
  $settings = array(
    'agency_id' => $agency_id,
  );
  $settings_js = 'var ask_vopros = ' . json_encode($settings) . ';';

  // The host variable is only for debugging.
  $base = 'http://' . variable_get('ding_bv_host', 'dev.biblioteksvagten.dk') . '/embed/';

  $l_options = array(
    'external' => TRUE,
    'query' => array(
      'agency_id' => $agency_id,
    ),
  );
  $page['footer'][] = array(
    '#prefix' => '<div class="ding-bv-tab">',
    '#suffix' => '</div>',
    '#markup' => l(t('Ask question'), $base . 'ask_question', $l_options),
    '#attached' => array(
      'js' => array(
        $base . 'question_modal.js' => array('type' => 'external'),
        $settings_js => array('type' => 'inline'),
      ),
      'css' => array(
        drupal_get_path('module', 'ding_bv') . '/ding_bv.css',
      ),
    ),
  );
}
