<?php

/**
 * @file
 * Provide a static tab which triggers a popup for sending a question to
 * Biblioteksvagten.dk.
 */

/**
 * Implements hook_menu().
 */
function ding_bv_menu() {
  $items['admin/config/services/ding_bv'] = array(
    'title' => 'Ask Biblioteksvagten.dk',
    'description' => 'Configure the tab for sending user questions to Biblioteksvagten.dk.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_bv_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_bv.admin.inc',
  );

  return $items;
}

/**
 * Preprocess variables for html.tpl.php
 *
 * This adds in our bottom tab. Using hook_page_build() is no good, as
 * panels_everywhere thoroughly disables it, so we use this instead.
 */
function ding_bv_preprocess_html(&$vars) {
  global $user;
  if ($agency_id = variable_get('ting_agency', '')) {
    $agency_id = 'DK-' . $agency_id;
  }
  else {
    $agency_id = variable_get('ding_bv_agency_id', '');
  }

  if (!$agency_id) {
    return;
  }

  // JavaScript settings var. Basic settings, id and mail.
  $settings = array(
    'agency_id' => $agency_id,
    'agency_mail' => variable_get('ding_bv_agency_mail', variable_get('site_mail', '')),
  );

  $answer_preference = variable_get('ding_bv_answer_preference', 'mail');
  if ($answer_preference !== 'mail') {
    $settings['answer_preference'] = $answer_preference;
  }

  // Check if a ding user is logged in and add in their name/zip/mail/phone if
  // they are.
  if (function_exists('ding_user_provider_profile') && $profile = ding_user_provider_profile($user)) {
    $module = ding_provider_get_provider_module_name('user');
    $mapping = array(
      'name' => 'full_name',
      'zip' => 'postal_code',
      'phone' => 'mobile_phone',
    );

    foreach ($mapping as $name => $field_suffix) {
      $field_name = 'field_' . $module . '_' . $field_suffix;

      $field_value = field_get_items('profile2', $profile, $field_name);
      if (!empty($field_value[0]['value'])) {
        $settings[$name] = $field_value[0]['value'];
      }
    }

    // Seems that there's some trouble getting the mail address from the
    // profile. It should've been copied to the mail of the Drupal user, so use
    // that.
    if (!empty($user->mail)) {
      $settings['mail'] = $user->mail;
    }
  }

  $settings_js = 'var ask_vopros = ' . json_encode($settings) . ';';

  // The host variable is only for debugging.
  $base = 'http://' . variable_get('ding_bv_host', 'adm.biblioteksvagten.dk') . '/embed/';

  // Add the JavaScript before testing visibility. This allows for hiding the
  // tab, but still being able to add a flat link which the JS will then pick up
  // and popupify.

  // We can't set the async attribute for an attached JS, so we build the script
  // element by hand, in the same way drupal_get_js() does.
  // Using async and defer is the currently recommend practice to avoid having
  // the page hang on the script.
  // @see https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/

  $element = array(
    '#tag' => 'script',
    '#value' => '',
    '#attributes' => array(
      'type' => 'text/javascript',
      'src' => $base . 'question_modal.js',
      'defer' => 'defer',
      'async' => 'async',
    ),
  );
  $vars['page']['page_bottom'][] = array(
    '#attached' => array(
      'js' => array(
        $settings_js => array('type' => 'inline'),
      ),
      'css' => array(
        drupal_get_path('module', 'ding_bv') . '/ding_bv.css',
      ),
    ),
    '#markup' => theme('html_tag', array('element' => $element)),
  );

  // Check visibility settings.
  $visibility_type = variable_get('ding_bv_visibility_type', 'not on');
  $visibility_pages = variable_get('ding_bv_visibility_pages', '');
  // If no pages are specified, show regardless of the type. This logic was
  // lifted from block_block_list_alter(). Look there for comments.
  if ($visibility_pages) {
    $visibility_pages = drupal_strtolower($visibility_pages);
    $path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
    $page_match = drupal_match_path($path, $visibility_pages);
    if ($path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $visibility_pages);
    }
    if ($page_match xor ($visibility_type == 'on')) {
      return;
    }
  }

  $l_options = array(
    'external' => TRUE,
    'query' => array(
      'agency_id' => $agency_id,
    ),
  );

  // Now add the tab.
  $vars['page']['page_bottom'][] = array(
    '#prefix' => '<div class="ding-bv-tab">',
    '#suffix' => '</div>',
    '#markup' => l(t('Ask question'), $base . 'ask-question', $l_options),
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'ding_bv') . '/ding_bv.css',
      ),
    ),
  );
}
